language: node_js
node_js:
- node
install:
- npm i -g @angular/cli
- npm ci
script:
- ng build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  local_dir: dist
  target_branch: master
  keep_history: true
  on:
    branch: src